version: '3'

services:
  master:
    image: husarion/foxglove-bridge:noetic-nightly
    command: roslaunch foxglove_bridge foxglove_bridge.launch port:=9090
    ports:
      - 11311:11311
      - 9090:9090
    restart: unless-stopped
  
  rtsp:
    image: bleyn/ros-rtsp:latest
    environment:
      - ROS_MASTER_URI=http://master:11311
    command: roslaunch camera_driver TriCamera.launch
    volumes:
      - ./launch:/ros_ws/src/ROS_RTSP/launch
    depends_on:
      - master
    network_mode: service:master
    restart: unless-stopped
  
  segmentation:
    build: .
    volumes:
      - ..:/workspace:cached
    environment:
      - ROS_MASTER_URI=http://master:11311
    command: sleep infinity
    depends_on:
      - master
    network_mode: service:master
    runtime: nvidia